### ISSUE TITLE
Random KeyNotFoundException when opening a form having Krypton controls

### ISSUE THREAD

**Issue by mbagattini** [ComponentFactory/Krypton#152]
From time to time, this kind of exception is raised in our software. I'm not able to track it down to a single cause, it appears randomly in different log files of our customers. 

Have anyone noticed it before? Do you have any suggestion about how to avoid it?

Here's the full stack trace:

`Stack trace: at System.Collections.Generic.Dictionary``2.get_Item(TKey key)
at System.Windows.Forms.ProfessionalColorTable.FromKnownColor(KnownColors color)
at System.Windows.Forms.ProfessionalColorTable.get_MenuStripGradientEnd()
at ComponentFactory.Krypton.Toolkit.PaletteProfessionalSystem.GetBackColor1(PaletteBackStyle style, PaletteState state)
at ComponentFactory.Krypton.Toolkit.PaletteRedirect.GetBackColor1(PaletteBackStyle style, PaletteState state)
at ComponentFactory.Krypton.Toolkit.PaletteBackInheritRedirect.GetBackColor1(PaletteState state)
at ComponentFactory.Krypton.Toolkit.PaletteBack.GetBackColor1(PaletteState state)
at ComponentFactory.Krypton.Toolkit.PaletteBack.GetBackColor1(PaletteState state)
at ComponentFactory.Krypton.Toolkit.PaletteBackInheritForced.GetBackColor1(PaletteState state)
at ComponentFactory.Krypton.Toolkit.RenderStandard.DrawBack(RenderContext context, Rectangle rect, GraphicsPath path, IPaletteBack palette, VisualOrientation orientation, PaletteState state, IDisposable memento)
at ComponentFactory.Krypton.Toolkit.ViewDrawPanel.RenderBefore(RenderContext context)
at ComponentFactory.Krypton.Toolkit.ViewComposite.Render(RenderContext context)
at ComponentFactory.Krypton.Toolkit.ViewManager.Paint(RenderContext context)
at ComponentFactory.Krypton.Toolkit.ViewManager.Paint(IRenderer renderer, PaintEventArgs e)
at ComponentFactory.Krypton.Toolkit.VisualPanel.OnPaint(PaintEventArgs e)
at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
at System.Windows.Forms.Control.OnPrint(PaintEventArgs e)
at System.Windows.Forms.Control.WmPrintClient(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Wagnerp** [comment]
Hi @mbagattini 

Is the error occurring with specific usage of controls, if so which controls are they?
