### ISSUE TITLE
Disabled KryptonComboBox WM_PAINT Exception for g.DrawString()

### ISSUE THREAD

**Issue by cuppm** [ComponentFactory/Krypton#171]
I know this is a long shot as I can't seem to reproduce this reliably, but here goes.  My application is in .Net 3.5 and I use DockPanelSuite with it to do a tabbed environment.

The issue usually only happens for me when it's open for long periods of time, and I'm guessing the GC gets automatically run.  But when the user goes back to the application and the disabled KryptonComboBox needs repainted, a `System.ArgumentException` is thrown with the message of "Parameter is not valid.":
```
at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
at ComponentFactory.Krypton.Toolkit.KryptonComboBox.InternalComboBox.WndProc(Message& m) in Krypton-master\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Toolkit\KryptonComboBox.cs:line 410
```
Here's the drawstring in the else block for when the control is disabled where it happens:
```c#
// Draw using a solid brush
try
{
	using (SolidBrush foreBrush = new SolidBrush(ForeColor))
		g.DrawString(Text, Font, foreBrush,
					 new RectangleF(rect.left, rect.top, rect.right - rect.left, rect.bottom - rect.top),
					 stringFormat);
}
catch(ArgumentException)
{
	using (SolidBrush foreBrush = new SolidBrush(ForeColor))
		g.DrawString(Text, _kryptonComboBox.GetComboBoxTripleState().PaletteContent.GetContentShortTextFont(PaletteState.Disabled), foreBrush,
					 new RectangleF(rect.left, rect.top, rect.right - rect.left, rect.bottom - rect.top),
					 stringFormat);
}
```
I was able to set a breakpoint for the debugger once the error started occurring and both `DrawString` calls will throw an exception.  I looked at the properties for `Font` and it will throw an exception for the `Height` property, which makes me think the font somehow got disposed?  Then when it tries to get the palette font, it appears to get the same reference and throws the same error.

If I set the control to enabled, it runs and displays just fine.

While debugging I tried setting the control's `Font` property to a new generic Font.  It runs fine the first time, but then gives an exception with message of "A generic error occurred in GDI+.".

If I create a new tab with a new KryptonComboBox and set it disabled, it appears to work correctly even if the others continue not to.

Any suggestions?

**Comment by cuppm** [comment]
Ok, I think I found the line difference that causes the issue:
````c#
kryptonComboBox1.StateDisabled.PopulateFromBase(PaletteState.Normal);
````
Since the `KryptonComboBox` doesn't contain a `ReadOnly` property like `TextBox` controls do, I was setting that line so a disabled control paints the same as readonly.  

Steps to reproduce:
1. Build of library with .NET 3.5
2. New .Net 3.5 WinForms project
3. Add a `KryptonComboBox` control to the form (a regular `System.Windows.Forms.Form`)
4. Set `Enabled = false` for control
5. Add the above line
6. Start the app
7. Minimize the app
8. Walk away and let the screensaver kick on and potentially monitor turn off.  My office one is set to 10 minutes, but it might need less time than that.
9. Wake up monitor and log back in
10. Restore the app window and it crashes
